version: "3"

services: 
    appsource:
        build: 
            context: .
        ports: 
            - "8000:8000"
        volumes: 
            - ./appsource:/appsource
        command: 
            sh -c "python manage.py runserver 0.0.0.0:8000"


